name: Android CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [created][created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Run unit tests
        run: ./gradlew test

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: tipjar-express-app
          path: app/build/outputs/apk/debug/app-debug.apk

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
      - name: Download APK artifact
        uses: actions/download-artifact@v3
        with:
          name: tipjar-express-app

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-notes:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
      - name: Generate changelog
        uses: mikepenz/release-changelog-builder-action@v3
        with:
          configuration: |
            categories:
              - title: '🚀 Features'
                labels: ['feature']
              - title: '🐛 Bug Fixes'
                labels: ['bug']
          token: ${{ secrets.GITHUB_TOKEN }}
